### ISSUE TITLE
Implement phone number lookup

### ISSUE THREAD

**Issue by seku** [tiramizoo/dovecote#2]
def lookup(number, country_code)
      phone_number = Dovecote::Msisdn.new(number, country_code.to_sym).to_s
      return if phone_number.blank? 
      headers = {'Authorization' => "AccessKey #{Dovecote.access_key}"}
      response = Excon.new("https://rest.messagebird.com/lookup/#{phone_number}").get(headers: headers)

      if (200..299).include?(response.status)
        #exists
...

**Comment by kubakrzempek** [comment]
@seku does #3 solve this issue?

**Comment by kubakrzempek** [comment]
@seku I guess we can push this one forward in #3
